# Petri networks

Here are only some tests with the snakes package to use on next session's 2 work.

In [20]:
import snakes.plugins
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
snakes.plugins.load(["gv", 'labels'], "snakes.nets", "nets")
from nets import *

path = 'images/'

net = PetriNet("mynet")
net.add_place(Place('p1', [dot]))
net.add_place(Place('p2'))
net.add_place(Place('p3', [dot]))
net.add_transition(Transition('t'))
net.add_input('p1', 't', Value(dot))
net.add_input('p3', 't', Value(dot))
net.add_output('p2', 't', Value(dot))
net.draw(f'{path}mynet33.png')

Graph(['node_0', 'node_2', 'node_3', 'node_1'], [])

In [21]:
t = net.transition('t')
m = t.modes()
t.fire(m.pop())
net.draw(f'{path}mynet2.ps')

Graph(['node_0', 'node_2', 'node_3', 'node_1'], [])

In [22]:
class Subject:
    def __init__(self, name, year_conclusion):
        self.name = name
        self.year_conclusion = year_conclusion
    def __str__(self):
        return str(self.name)

class Aluno:
    def __init__(self, ident, subjects):
        self.ident = ident
        self.subjects = subjects
    def __str__(self):
        return str(self.ident)
    def __repr__(self):
        return str(self.ident)
        
student = Aluno('Paulo', Subject('calculo1', '2014.1'))
print(student)
classes = PetriNet('MyNet2')
p1 = Place('p1', [student, dot])
#p1.label('aaa')
classes.add_place(p1)
classes.add_place(Place('p2'))
classes.add_place(Place('p3', [dot, student]))
classes.place('p2')

classes.add_transition(Transition('t1'))
classes.add_input('p1', 't1', Value(student))


classes.add_input('p3', 't1', Value(student))



classes.add_output('p2', 't1', Value(student))



classes.draw(f'{path}mynet44.png')
t1 = classes.transition('t1')
print(t1)
m1 = t1.modes()
print(m1)
t1.fire(m1.pop())
print(m1)
graph = classes.draw(f'{path}mynet45.png' )

Paulo
t1
[Substitution()]
[]

# Applying Petri To Educational Problems

In this new section, we will explore how to model a grade of students in order to visualize in which subjects students get most stuck on, by studying the flow of students in calculus chairs of the Science and Technology course of Federal University of Rio Grande do Norte. We will first do for calculus students and later, if possible, to all the subjects on S&T's curriculum.

## Importing libs and students data

In [23]:
import snakes.plugins
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
snakes.plugins.load(["gv", 'labels'], "snakes.nets", "nets")
from nets import *
import pandas as pd

In [65]:
components = pd.read_csv('data/componentes-curriculares-presenciais.csv', sep=';')
print(components.columns.tolist())
components[components['id_componente'] == 57587]

['id_componente', 'tipo_componente', 'codigo', 'nivel', 'nome', 'unidade_responsavel', 'ch_teorico', 'ch_pratico', 'ch_estagio', 'ch_total', 'ch_dedicada_docente', 'ch_ead', 'cr_max_ead', 'permite_horario_flexivel', 'qtd_unidades', 'procedimentos_avaliacao', 'equivalencia', 'pre_requisito', 'co_requisito', 'ementa', 'bibliografia', 'objetivos', 'conteudo', 'competencias_habilidades', 'referencias', 'ano_programa', 'periodo_programa', 'modalidade', 'curso_componente']

,id_componente,tipo_componente,codigo,nivel,nome,unidade_responsavel,ch_teorico,ch_pratico,ch_estagio,ch_total,...,ementa,bibliografia,objetivos,conteudo,competencias_habilidades,referencias,ano_programa,periodo_programa,modalidade,curso_componente
22569,57587,MÓDULO,ECT2103,G,CÁLCULO I,ESCOLA DE CIÊNCIAS E TECNOLOGIA,60,0,0,60,...,Limites e continuidade. Derivada. Aplicações d...,NaN,- Introduzir e capacitar o aluno a entender e ...,1. Limites\r\n1.1 Definição. Limites laterais....,NaN,NaN,2019.0,2.0,Presencial,CIÊNCIAS E TECNOLOGIA

In [25]:
students = pd.read_csv('data/df_alunos20151.csv')
students.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20334 entries, 0 to 20333
Data columns (total 25 columns):
Unnamed: 0                  20334 non-null int64
descricao                   20334 non-null object
discente                    20334 non-null object
id_curso                    20334 non-null float64
id_turma                    20334 non-null int64
media_final                 14640 non-null object
codigo_turma                20334 non-null object
id_componente_curricular    20334 non-null int64
ano                         20334 non-null int64
periodo                     20334 non-null int64
data_inicio                 20334 non-null object
data_fim                    20334 non-null object
data_consolidacao           20333 non-null object
agrupadora                  20334 non-null bool
id_turma_agrupadora         4674 non-null float64
id_componente               17445 non-null float64
codigo                      17445 non-null object
nome                        17445 non-null object
unidade_responsavel         17445 non-null object
pre_requisito               7696 non-null object
co_requisito                302 non-null object
ano_programa                17444 non-null float64
periodo_programa            17444 non-null float64
curso_componente            16411 non-null object
anoperiodo                  20334 non-null int64
dtypes: bool(1), float64(5), int64(6), object(13)
memory usage: 3.7+ MB

In [26]:
#Counting unique students on the dataset
students['discente'].unique().shape

(714,)

In [27]:
students[students['descricao'] == 'CANCELADO'].shape

(2037, 25)

As we can see, there are 714 students who entered the Science and Technology course in the first semester of 2015. Unfortunately, this does not mean that all of this students will finish the course on expected time of two years or would quit. This will also affect our petri network model in the future.

The reason for using these students is because after up from this period, course's grade was changed, and students from previous semesters would affect in our analysis, because how subjects were teached on the previous curriculum could affect their performance in how subjects are teached from 2015 and beyond.

## Preparing Students Object

Now we are going to create a student's model tu use as the token color on the colored petri network. Also, we will clean even more the data so we have only students who have not canceled their registration of the course.

In [28]:
students_not_null = students.dropna(subset=['media_final'])
students_not_null.head()

,Unnamed: 0,descricao,discente,id_curso,id_turma,media_final,codigo_turma,id_componente_curricular,ano,periodo,...,id_componente,codigo,nome,unidade_responsavel,pre_requisito,co_requisito,ano_programa,periodo_programa,curso_componente,anoperiodo
0,720645,REPROVADO POR MÉDIA E POR FALTAS,6360ce81e659feee39452aa8cd111beb,10320810.0,1242589,"0,0",03,57587,2015,1,...,57587.0,ECT2103,CÁLCULO I,ESCOLA DE CIÊNCIAS E TECNOLOGIA,NaN,NaN,2019.0,2.0,CIÊNCIAS E TECNOLOGIA,20151
1,720648,CANCELADO,e5930e3c2c83d80ef671058e553b96b9,10320810.0,1242589,"1,3",03,57587,2015,1,...,57587.0,ECT2103,CÁLCULO I,ESCOLA DE CIÊNCIAS E TECNOLOGIA,NaN,NaN,2019.0,2.0,CIÊNCIAS E TECNOLOGIA,20151
2,720651,REPROVADO,dab92c51983ebd2459e35439f103f686,10320810.0,1242589,"0,7",03,57587,2015,1,...,57587.0,ECT2103,CÁLCULO I,ESCOLA DE CIÊNCIAS E TECNOLOGIA,NaN,NaN,2019.0,2.0,CIÊNCIAS E TECNOLOGIA,20151
3,720654,REPROVADO,d258f7fb1f7e7afa8f7b25b295307c7a,10320810.0,1242589,"0,0",03,57587,2015,1,...,57587.0,ECT2103,CÁLCULO I,ESCOLA DE CIÊNCIAS E TECNOLOGIA,NaN,NaN,2019.0,2.0,CIÊNCIAS E TECNOLOGIA,20151
4,720657,REPROVADO,23b37af4ddf3030c9eb44e153457ed60,10320810.0,1242589,"3,0",03,57587,2015,1,...,57587.0,ECT2103,CÁLCULO I,ESCOLA DE CIÊNCIAS E TECNOLOGIA,NaN,NaN,2019.0,2.0,CIÊNCIAS E TECNOLOGIA,20151

In [29]:
students['descricao'].value_counts(ascending=False)

APROVADO POR NOTA                   5364
APROVADO                            4462
INDEFERIDO                          2799
REPROVADO                           2798
CANCELADO                           2037
REPROVADO POR MÉDIA E POR FALTAS    1274
TRANCADO                             635
DESISTENCIA                          469
EXCLUIDA                             442
REPROVADO POR NOTA                    40
REPROVADO POR FALTAS                   8
REPROVADO POR NOTA E FALTA             6
Name: descricao, dtype: int64

In [30]:
students_not_null['descricao'].value_counts(ascending=False)

APROVADO POR NOTA                   5364
APROVADO                            4462
REPROVADO                           2798
REPROVADO POR MÉDIA E POR FALTAS    1274
CANCELADO                            678
REPROVADO POR NOTA                    40
REPROVADO POR FALTAS                   8
TRANCADO                               6
REPROVADO POR NOTA E FALTA             6
EXCLUIDA                               3
DESISTENCIA                            1
Name: descricao, dtype: int64

In [125]:
excluded = students['descricao'] != 'EXCLUIDA'
give_up = students['descricao'] != 'DESISTENCIA'
cancelled = students['descricao'] != 'CANCELADO'
indefered = students['descricao'] != 'INDEFERIDO'

students_final = students[cancelled & indefered & give_up & excluded]
students_final.descricao.value_counts(ascending=False)

APROVADO POR NOTA                   5364
APROVADO                            4462
REPROVADO                           2798
REPROVADO POR MÉDIA E POR FALTAS    1274
TRANCADO                             635
REPROVADO POR NOTA                    40
REPROVADO POR FALTAS                   8
REPROVADO POR NOTA E FALTA             6
Name: descricao, dtype: int64

In [126]:
print(students_final.discente.unique().shape)
students_final.set_index('descricao').isna().sum(level=0)['media_final']

(619,)

descricao
REPROVADO POR MÉDIA E POR FALTAS      0.0
REPROVADO                             0.0
APROVADO POR NOTA                     0.0
TRANCADO                            629.0
APROVADO                              0.0
REPROVADO POR NOTA                    0.0
REPROVADO POR NOTA E FALTA            0.0
REPROVADO POR FALTAS                  0.0
Name: media_final, dtype: float64

In [127]:
students.set_index('descricao').isna().sum(level=0)['media_final']

descricao
REPROVADO POR MÉDIA E POR FALTAS       0.0
CANCELADO                           1359.0
REPROVADO                              0.0
APROVADO POR NOTA                      0.0
TRANCADO                             629.0
EXCLUIDA                             439.0
DESISTENCIA                          468.0
APROVADO                               0.0
INDEFERIDO                          2799.0
REPROVADO POR NOTA                     0.0
REPROVADO POR NOTA E FALTA             0.0
REPROVADO POR FALTAS                   0.0
Name: media_final, dtype: float64

In [128]:
#Making final dataset, filling students that 'locked' their chair with grades 0.
filling_nan = students_final.media_final.copy()
filling_nan.fillna(value=0, inplace=True)
students_final.loc['media_final'] = filling_nan
#students_final.dropna(subset=['nome'], inplace=True)
print(students_final.set_index('descricao').isna().sum(level=0)['media_final'])
print('\n\n',students_final.info())

descricao
REPROVADO POR MÉDIA E POR FALTAS      0.0
REPROVADO                             0.0
APROVADO POR NOTA                     0.0
TRANCADO                            629.0
APROVADO                              0.0
REPROVADO POR NOTA                    0.0
REPROVADO POR NOTA E FALTA            0.0
REPROVADO POR FALTAS                  0.0
Name: media_final, dtype: float64
<class 'pandas.core.frame.DataFrame'>
Index: 14588 entries, 0 to media_final
Data columns (total 25 columns):
Unnamed: 0                  14587 non-null float64
descricao                   14587 non-null object
discente                    14587 non-null object
id_curso                    14587 non-null float64
id_turma                    14587 non-null float64
media_final                 13958 non-null object
codigo_turma                14587 non-null object
id_componente_curricular    14587 non-null float64
ano                         14587 non-null float64
periodo                     14587 non-null float64
data_inicio                 14587 non-null object
data_fim                    14587 non-null object
data_consolidacao           14587 non-null object
agrupadora                  14587 non-null float64
id_turma_agrupadora         3236 non-null float64
id_componente               12430 non-null float64
codigo                      12430 non-null object
nome                        12430 non-null object
unidade_responsavel         12430 non-null object
pre_requisito               5800 non-null object
co_requisito                226 non-null object
ano_programa                12430 non-null float64
periodo_programa            12430 non-null float64
curso_componente            11602 non-null object
anoperiodo                  14587 non-null float64
dtypes: float64(12), object(13)
memory usage: 2.9+ MB


 None

/home/laboratorio7/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

In [129]:
print(students_final[students_final['discente'] == '6360ce81e659feee39452aa8cd111beb'].shape)
students_final[students_final['discente'] == '6360ce81e659feee39452aa8cd111beb'].head()

#a = students_final[students_final['discente'] == '6360ce81e659feee39452aa8cd111beb'].iterrows()

(33, 25)

,Unnamed: 0,descricao,discente,id_curso,id_turma,media_final,codigo_turma,id_componente_curricular,ano,periodo,...,id_componente,codigo,nome,unidade_responsavel,pre_requisito,co_requisito,ano_programa,periodo_programa,curso_componente,anoperiodo
0,720645.0,REPROVADO POR MÉDIA E POR FALTAS,6360ce81e659feee39452aa8cd111beb,10320810.0,1242589.0,"0,0",03,57587.0,2015.0,1.0,...,57587.0,ECT2103,CÁLCULO I,ESCOLA DE CIÊNCIAS E TECNOLOGIA,NaN,NaN,2019.0,2.0,CIÊNCIAS E TECNOLOGIA,20151.0
135,725213.0,APROVADO,6360ce81e659feee39452aa8cd111beb,10320810.0,1242292.0,"8,0",03,57602.0,2015.0,1.0,...,57602.0,ECT2105,PRÁTICAS DE LEITURA E ESCRITA I,ESCOLA DE CIÊNCIAS E TECNOLOGIA,NaN,NaN,2019.0,2.0,CIÊNCIAS E TECNOLOGIA,20151.0
214,727629.0,APROVADO POR NOTA,6360ce81e659feee39452aa8cd111beb,10320810.0,1242298.0,"5,0",03,57605.0,2015.0,1.0,...,57605.0,ECT2106,"CIÊNCIA, TECNOLOGIA E SOCIEDADE",ESCOLA DE CIÊNCIAS E TECNOLOGIA,NaN,NaN,2019.0,2.0,CIÊNCIAS E TECNOLOGIA,20151.0
1469,759435.0,APROVADO,6360ce81e659feee39452aa8cd111beb,10320810.0,1242272.0,"7,2",03E,57600.0,2015.0,1.0,...,57600.0,ECT2104,QUÍMICA GERAL,ESCOLA DE CIÊNCIAS E TECNOLOGIA,NaN,NaN,2019.0,2.0,CIÊNCIAS E TECNOLOGIA,20151.0
1553,768168.0,APROVADO POR NOTA,6360ce81e659feee39452aa8cd111beb,10320810.0,1242227.0,"5,3",03,57586.0,2015.0,1.0,...,57586.0,ECT2101,PRÉ-CÁLCULO,ESCOLA DE CIÊNCIAS E TECNOLOGIA,NaN,NaN,2019.0,2.0,CIÊNCIAS E TECNOLOGIA,20151.0

## Preparing Petri Network Color

The next part of the work is to prepare the color of of marcations for the colored petri network system. We will use the students' characteristics described in the *students_final* dataframe, in which we dropped students with registration on the subject described as cancelled, indefered and locked.

In [131]:
import pandas as pd


class Student:
    def __init__(self, student_id):
        self.student_id = student_id
        self.subjects = []
    def __repr__(self):
        return str(self.student_id)
    def __str__(self):
        return f"Student id: {self.student_id}\nStudent's subjects history: {self.subjects}"
    def add_subject(self, discipline):
        self.subjects.append(discipline)
    def require_subject_info(self, students):
        '''
        Returns wether or not the student's subjects object is filled with the students data.
        If the subjects list was empty, it returns True and fills the list with all the necessary
        data of the specified student.
        Parameter:
        * students: students' dataframe with info of all students who entered S&T course in 2015.1.
        '''
        student_table = students[students['discente'] == self.student_id]
        rows_student = student_table.iterrows()
        if self.subjects == []:
            for row in rows_student:
                series = pd.Series(row)
                discipline = Discipline(
                    ident = row[1]['id_componente'],
                    name = row[1]['nome'],
                    semester = row[1]['anoperiodo'],
                    status = row[1]['descricao']
                )
                self.subjects.append(discipline)
            return True
        else:
            return False
        def correct_status(self):
            #corrigir a forma que representa o status naquela disciplina
            return True

        
class Discipline:
    def __init__(self, ident, name, semester, status):
        '''
        constructor of the class Discipline, it has 4 parameters:
        * ident: code of the discipline to identify on the components table
        * name: name of the subject
        * status: student's final status this subject
        * semester: semester in which the student attended to this classroom
        '''
        self.ident = ident
        self.name = name
        self.semester = semester
        self.status = status
    def __str__(self):
        return f'Component id: {self.ident}, \nDiscipline name: {self.name}, \nDiscipline semester: {self.semester}, \nStudent status: {self.status}\n'
    def __repr__(self):
        return f'Component id: {self.ident}, Discipline name: {self.name}, Discipline semester: {self.semester}, Student status: {self.status}\n'
        
teste = Student(student_id='6360ce81e659feee39452aa8cd111beb')
teste.require_subject_info(students_final)
print(teste)

Student id: 6360ce81e659feee39452aa8cd111beb
Student's subjects history: [Component id: 57587.0, Discipline name: CÁLCULO I, Discipline semester: 20151.0, Student status: REPROVADO POR MÉDIA E POR FALTAS
, Component id: 57602.0, Discipline name: PRÁTICAS DE LEITURA E ESCRITA I, Discipline semester: 20151.0, Student status: APROVADO
, Component id: 57605.0, Discipline name: CIÊNCIA, TECNOLOGIA E SOCIEDADE, Discipline semester: 20151.0, Student status: APROVADO POR NOTA
, Component id: 57600.0, Discipline name: QUÍMICA GERAL, Discipline semester: 20151.0, Student status: APROVADO
, Component id: 57586.0, Discipline name: PRÉ-CÁLCULO, Discipline semester: 20151.0, Student status: APROVADO POR NOTA
, Component id: 2051005.0, Discipline name: VETORES E GEOMETRIA ANALÍTICA, Discipline semester: 20151.0, Student status: REPROVADO
, Component id: 57597.0, Discipline name: LÓGICA DE PROGRAMAÇÃO, Discipline semester: 20152.0, Student status: REPROVADO
, Component id: 57607.0, Discipline name: MEIO AMBIENTE E DESENVOLVIMENTO URBANO, Discipline semester: 20152.0, Student status: APROVADO
, Component id: 57606.0, Discipline name: GESTÃO E ECONOMIA DA CIÊNCIA, TECNOLOGIA E INOVAÇÃO, Discipline semester: 20152.0, Student status: APROVADO POR NOTA
, Component id: 2051005.0, Discipline name: VETORES E GEOMETRIA ANALÍTICA, Discipline semester: 20152.0, Student status: REPROVADO
, Component id: 57603.0, Discipline name: PRÁTICAS DE LEITURA E ESCRITA II, Discipline semester: 20152.0, Student status: APROVADO POR NOTA
, Component id: 57604.0, Discipline name: PRÁTICA DE LEITURA EM INGLÊS, Discipline semester: 20152.0, Student status: APROVADO
, Component id: nan, Discipline name: nan, Discipline semester: 20161.0, Student status: APROVADO
, Component id: 57587.0, Discipline name: CÁLCULO I, Discipline semester: 20161.0, Student status: APROVADO POR NOTA
, Component id: 57623.0, Discipline name: METODOLOGIA CIENTÍFICA E TECNOLÓGICA, Discipline semester: 20161.0, Student status: APROVADO POR NOTA
, Component id: 57624.0, Discipline name: CIÊNCIA E TECNOLOGIA DOS MATERIAIS, Discipline semester: 20161.0, Student status: APROVADO POR NOTA
, Component id: 57598.0, Discipline name: LINGUAGEM DE PROGRAMAÇÃO, Discipline semester: 20161.0, Student status: REPROVADO POR MÉDIA E POR FALTAS
, Component id: nan, Discipline name: nan, Discipline semester: 20162.0, Student status: APROVADO POR NOTA
, Component id: nan, Discipline name: nan, Discipline semester: 20162.0, Student status: REPROVADO
, Component id: 57592.0, Discipline name: INTRODUÇÃO À FÍSICA CLÁSSICA I, Discipline semester: 20162.0, Student status: APROVADO POR NOTA
, Component id: 57588.0, Discipline name: CÁLCULO II, Discipline semester: 20162.0, Student status: REPROVADO
, Component id: 57589.0, Discipline name: ÁLGEBRA LINEAR, Discipline semester: 20162.0, Student status: REPROVADO
, Component id: 57591.0, Discipline name: PROBABILIDADE E ESTATÍSTICA, Discipline semester: 20162.0, Student status: REPROVADO
, Component id: 57589.0, Discipline name: ÁLGEBRA LINEAR, Discipline semester: 20171.0, Student status: TRANCADO
, Component id: 57593.0, Discipline name: INTRODUÇÃO À FÍSICA CLÁSSICA II, Discipline semester: 20171.0, Student status: REPROVADO
, Component id: 57588.0, Discipline name: CÁLCULO II, Discipline semester: 20171.0, Student status: REPROVADO
, Component id: nan, Discipline name: nan, Discipline semester: 20171.0, Student status: APROVADO POR NOTA
, Component id: 57591.0, Discipline name: PROBABILIDADE E ESTATÍSTICA, Discipline semester: 20171.0, Student status: APROVADO POR NOTA
, Component id: 57595.0, Discipline name: FÍSICA EXPERIMENTAL I, Discipline semester: 20172.0, Student status: APROVADO POR NOTA
, Component id: 57593.0, Discipline name: INTRODUÇÃO À FÍSICA CLÁSSICA II, Discipline semester: 20172.0, Student status: REPROVADO
, Component id: 57588.0, Discipline name: CÁLCULO II, Discipline semester: 20172.0, Student status: REPROVADO
, Component id: 57627.0, Discipline name: EXPRESSÃO GRÁFICA, Discipline semester: 20172.0, Student status: TRANCADO
, Component id: nan, Discipline name: nan, Discipline semester: 20172.0, Student status: APROVADO POR NOTA
]